### PR TITLE
Implement old django website parts in nuxt

### PR DESCRIPTION
**Pull request by kelsos**
# TODO

- [x] Fix country label position
- [x] Add country flag in select [link this](https://twitter.com/wesbos/status/1479496816693592065?t=FxwYYRhUGctRRujFUsJLxg&s=09)
- [x] Show a prompt/link to buy a subscription when you have 0 subscriptions
- [x] Show a prompt to renew a subscription when you don't have an active subscription
- [x] Fix Paypal checkout
- [ ] Implement products pages (Summary/Details)
    - [x] Summary
    - [ ] Details
- [x] Implement dropdown to select a new plan

### CODE REVIEW

**Comment by yabirgb** [comment]
Could be possible to show here something like `No subscriptions yet` instead of showing a empty pagination? In addition it shows page 1 of 0 that is a bit odd

image

**Comment by kelsos** [comment]
> Could be possible to show here something like `No subscriptions yet` instead of showing a empty pagination? In addition it shows page 1 of 0 that is a bit odd
> 
> image

Sure let me know if you notice anything else @yabirgb

**Comment by yabirgb** [comment]
Found that if you are logged in and click again in manage premium it points you to the login screen again instead of showing your information

**Comment by kelsos** [comment]
> Found that if you are logged in and click again in manage premium it points you to the login screen again instead of showing your information.
> 

Can you see for any errors in the console/requests?
> Also in brave the input for the country is empty
> 
Yes the label for the dropdown is in the wrong place
> image

**Pull request merged**
