### PR TITLE
Remove FTX from supported exchanges

### PR DESCRIPTION
**Pull request by vincenttaglia**
Took a look at the website recently when recommending Rotki and this jumped out at me. I think it's probably a good idea to go ahead and remove, especially with the API being down, likely permanently.

Keep up the great work!

### CODE REVIEW

**Comment by yabirgb** [comment]
Hello @vincenttaglia. Thank you! Could you check the linter error?

**Review by LefterisJP — COMMENTED** [review]
Hmm weird. Was the linter added after the site was created? It seems to suggest a change from what is already there. @kelsos ?

**Comment by vincenttaglia** [comment]
@LefterisJP it looks like removing the FTX entry made eslint decide it was time to bring that array from multi-line to single-line. Adding it back and eslint wants it to be multi-line again.

Latest commit should pass tests now.

**Review by LefterisJP — APPROVED** [review]
LGTM. Will merge it. We have not really removed the FTX code from the app yet btw, but querying FTX data does not work, since FTX does not exist :rofl:

**Pull request merged**
