### PR TITLE
feat: integration list page

### PR DESCRIPTION
**Pull request by lukicenturi**

### CODE REVIEW

**Comment by kelsos** [comment]
`https://raw.githubusercontent.com/rotki/rotki` needs to be added to the CSP, with CSP enabled the images won't load.

**Comment by kelsos** [comment]
not sure if I am missing something but aren't we supposed to move the menu entries for jobs to the bottom instead?

**Comment by lukicenturi** [comment]
> not sure if I am missing something but aren't we supposed to move the menu entries for jobs to the bottom instead?

yeah but I was thinking to do it in different PR

**Comment by lukicenturi** [comment]
The CSP is added now, should load the image

**Pull request merged**
